name = "NReco"
uuid = "c63725ce-1dd3-4448-9322-cc096a1b1cd3"
authors = ["J.J. Gomez-Cadenas <jjgomezcadenas@gmail.com> and contributors"]
version = "0.1.0"

[deps]
ATools = "f146b9ee-cb39-4cb9-873f-768aeedb20d7"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Clustering = "aaaa29a8-35af-508c-8bc3-b662a17a0fe5"
Configurations = "5218b696-f38b-4ac9-8b61-a12ec717816d"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PhysicalConstants = "5ad8b20f-a522-5ce9-bfc9-ddf1d5bda6ab"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
StatsModels = "3eaba693-59b7-5ba5-a881-562e759f1c8d"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
ArgParse = "1"
CSV = "0.8, 0.9"
Clustering = "0.14"
DataFrames = "1"
Distributions = "0.25"
Glob = "1"
HDF5 = "0.15"
PhysicalConstants = "0.2"
Plots = "1"
StatsBase = "0.33"
StatsModels = "0.6"
Unitful = "1"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
